import TopNavigation from "@/components/top-navigation";
import { trpc } from "@/utils/trpc";
import Head from "next/head";
import { useRouter } from "next/router";


const CollectionPage = () => {
  const router = useRouter();
  const collectionName = router.query.id as string;
  console.log(collectionName);
  const collection = trpc.useQuery(["shop.get-all", { collection: collectionName }]);

  if (collection.isLoading) {
    return <div>Loading...</div>
  }

  return (
    <>
      <Head>
        <title>{collectionName} | CRWN Clothing</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <TopNavigation />
        <div className="items-center flex flex-col">
          <h1 className="text-7xl mb-5 font-bold select-none uppercase p-2">{collectionName}</h1>
        </div>
        <div className="grid sm:grid-cols-2 xl:grid-cols-3  grid-cols-1">
          {collection.data?.map(item =>
            <div className="p-2">
              <div className="border-solid items-center flex flex-col rounded-2xl">
                <img className="object-cover h-[300px] rounded-xl w-[222px] overflow-hidden" src={item.imageUrl} />
              </div>
              <div className="p-1 ml-[125px]">
                <p className="">{item.name}</p>
                <p className="">{item.price}</p>
              </div>
            </div>
          )}
        </div>
      </main>
    </>
  )

}

export default CollectionPage;