import TopNavigation from "@/components/top-navigation";
import { useCartStore } from "@/store/cartStore";
import ShopItemType from "@/types/shop-item-type";
import { trpc } from "@/utils/trpc";
import Head from "next/head";
import { useRouter } from "next/router";


const CollectionPage = () => {
  const router = useRouter();
  const routeName = router.query.id as string;
  const collection = trpc.useQuery(["shop.get-collection", { routeName: routeName }]); 
  const addToCart = useCartStore((state) => state.addToCart);

  if (collection.isLoading) {
    return <div>Loading...</div>
  }

  const addItem = (product: ShopItemType) => {
    addToCart(product, 1);
  }

  return (
    <>
      <Head>
        <title>{routeName} | CRWN Clothing</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <TopNavigation />
        <div className="bg-white">
          <h1 className="text-purple-900 flex flex-col text-center font-bold text-6xl uppercase">{routeName}</h1>
          <div className="mx-auto max-w-2xl py-16 px-4 sm:py-24 sm:px-6 lg:max-w-7xl lg:px-8">
            <div className="grid grid-cols-1 gap-y-10 gap-x-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 xl:gap-x-8">
              {collection.data?.map((product: ShopItemType) => (
                <a key={product.id} className="group cursor-pointer" onClick={() => addItem(product)}>
                  <div className="aspect-w-1 aspect-h-1 w-full overflow-hidden rounded-lg bg-gray-200 xl:aspect-w-7 xl:aspect-h-8 border-purple-900 border-2">
                    <img
                      src={product.imageUrl}
                      // alt={product.imageAlt}
                      className="h-full w-full object-cover object-center group-hover:opacity-75"
                    />
                  </div>
                  <h2 className="mt-4 text-sm text-gray-700">{product.name}</h2>
                  <p className="mt-1 text-lg font-medium text-gray-900">{product.price}</p>
                </a>
              ))}
            </div>
          </div>
        </div>
      </main>
    </>
  )

}

export default CollectionPage;