import type { NextPage } from "next";
import Head from "next/head";
import TopNavigation from "@/components/top-navigation";
import CollectionCard from "../components/collection-card";
import { sendCollectionSchema } from "@/server/router/routes/shopRoutes";
import SHOP_DATA from "../server/router/routes/data";
import { ShopItemType } from "@/types/shop-item-type";
import { trpc } from "@/utils/trpc";

const Home: NextPage = () => {
  // const { mutate } = trpc.useMutation(["shop.fill-data"]);
  // const go = () => {
  //   SHOP_DATA.map((coll) => {
  //     const data: ShopItemType[] = [];
  //     const routeName = coll.routeName;
  //     coll.items.map((item) => {
  //       data.push({
  //         itemId: item.id,
  //         name: item.name,
  //         price: item.price,
  //         imageUrl: item.imageUrl,
  //         routeName
  //       })
  //     });
  //     mutate(data);
  //   })
  // }

  return (
    <>
      <Head>
        <title>CRWN Clothing</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <TopNavigation />
        {/* <button className={"bg-red-900"} onClick={() => go()}>XXXXX</button> */}
        <div className="mb-6" />
        <div className="flex flex-wrap justify-around">
          <CollectionCard collection={"mens"} imageUrl={"https://i.ibb.co/R70vBrQ/men.png"} />
          <CollectionCard collection={"womens"} imageUrl={"https://i.ibb.co/GCCdy8t/womens.png"} />
        </div>
        <div className="mt-5" />
        <div className="flex flex-wrap justify-around">
          <CollectionCard collection={"jackets"} imageUrl={"https://i.ibb.co/px2tCc3/jackets.png"} />
          <CollectionCard collection={"sneakers"} imageUrl={"https://i.ibb.co/0jqHpnp/sneakers.png"} />
          <CollectionCard collection={"hats"} imageUrl={"https://i.ibb.co/cvpntL1/hats.png"} />
        </div>
      </main>
    </>
  );
};

export default Home;