import TopNavigation from "@/components/top-navigation"
import Head from "next/head";
import CollectionItem from "@/components/collection-item";

const Shop = () => {


  return (
    <>
      <Head>
        <title>Shop | CRWN Clothing</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <TopNavigation />
        <CollectionItem coll="hats" />
        <div className="mt-5" />
        <CollectionItem coll="sneakers" />
        <div className="mt-5" />
        <CollectionItem coll="jackets" />
        <div className="mt-5" />
        <CollectionItem coll="womens" />
        <div className="mt-5" />
        <CollectionItem coll="mens" />
      </main>
    </>
  )
}

export default Shop;